chore(EndpointDataReferenceReceiverRegistry): make the transfer process in EndpointDataReferenceReceiverRegistry fail if no receivers are registered.
eclipse-edc/Connector pull request #2330
Opened 2022-12-12 10:29 UTC by majadlymhmd

## What this PR changes/adds
chore(EndpointDataReferenceReceiverRegistry): make the transfer process in EndpointDataReferenceReceiverRegistry fail if no receivers are registered.

## Why it does that

To ensure that if no receivers are registered the transfer process fails.
## Further notes

## Linked Issue(s)

Closes # <--  #2228

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

2022-12-12 14:43 UTC, juliapampus requested changes
Changed files from #2246 seem to be added within this PR. Pls drop the older commit on this branch.

2022-12-13 08:00 UTC, ndr-brt commented on core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImpl.java
> +        if (!receivers.isEmpty()) {
Better flip the `if` condition, when a branch is one liner is always better to have it visible at the top

2022-12-13 08:00 UTC, ndr-brt commented on core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImpl.java
> +            throw new EdcException("There are no registered receivers.");
please return `failedFuture`

2022-12-13 14:09 UTC, ndr-brt approved these changes

2022-12-14 11:59 UTC, juliapampus approved these changes

2022-12-14 16:17 UTC, merged