doc: create first draft of IDS architecture documents
eclipse-edc/Connector pull request #2448
Opened 2023-01-31 15:36 UTC by jimmarino

This is a draft PR for documents outlining the architecture of EDC IDS protocol support.

## Linked Issue(s)

Part of #2429

2023-02-09 09:34 UTC, florianrusch-zf requested changes
Still not finished the review, but I think as we already want to go forward my comments could eventually already be valuable.

2023-02-10 07:06 UTC, jimmarino commented on docs/developer/architecture/ids-next/README.md
> +# IDS-Next Architecture
DRs will come later and follow these documents. The DRs will lay out specific decisions that have an architectural impact; these documents lay out the overall architecture.

2023-02-10 07:07 UTC, jimmarino commented on docs/developer/architecture/ids-next/contract-negotiation-architecture.md
> +table) and updating the `ContractNegotition`.
I specifically wanted to call out the use of a table for correlation here.

2023-02-10 07:10 UTC, jimmarino commented on docs/developer/architecture/ids-next/ids-endpoints-services-architecture.md
> +    private static final String DCAT_DATA_SERVICE = "http://www.w3.org/ns/dcat/DataService";
Some could be

2023-02-20 09:04 UTC, juliapampus requested changes

2023-02-20 09:04 UTC, juliapampus commented on docs/developer/architecture/ids-dataspace-protocol/README.md
> +The EDC will be upgraded to implement and be fully compliant to the __IDS Next__ protocol specifications. These include:
"IDS Next" is still mentioned in all of your documents.

2023-02-20 09:04 UTC, juliapampus commented on docs/developer/architecture/ids-dataspace-protocol/README.md
> +# IDS Dataspace Protocol Architecture
Without "IDS"

2023-02-22 10:56 UTC, ndr-brt approved these changes
All good, I'm a little confused because IDS and everyone always wrote about "data space" and now we're calling it "dataspace" without the white space. For that matter, I prefer the latter.

2023-02-23 07:58 UTC, juliapampus approved these changes

2023-02-23 08:45 UTC, merged