feat: add JSON-LD transformers
eclipse-edc/Connector pull request #2656
Opened 2023-03-29 14:28 UTC by ronjaquensel

## What this PR changes/adds

Adds a `dsp-transform` module for transforming between EDC model and JSON-LD. Updates the Catalog model to include `Datasets`, `Distributions` and `DataServices`.

## Why it does that

JSON-LD support is required for implementation of the dataspace protocol.

## Further notes

As to not be dependent on PR #2653, this PR includes also the interfaces and base classes for JSON-LD transformers. Once PR #2653 is merged, this PR will be updated and move the interfaces and base classes to the `json-ld` module.

Feedback from the closed PR #2620 has been applied, only adding constants for the DCAT/ODRL types and properties is yet to be done.

## Linked Issue(s)

Relates #2474 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

2023-03-30 13:11 UTC, jimmarino requested changes
See my comment

2023-04-04 08:45 UTC, ndr-brt approved these changes
looks good!

2023-04-04 08:45 UTC, ndr-brt commented on data-protocols/dsp/dsp-transform/src/main/java/org/eclipse/edc/protocol/dsp/transform/transformer/to/JsonObjectToConstraintTransformer.java
> +        //TODO check for type of constraint (atomic, and, or, ...)
could this todo converted in an issue?

2023-04-04 08:57 UTC, ronjaquensel commented on data-protocols/dsp/dsp-transform/src/main/java/org/eclipse/edc/protocol/dsp/transform/transformer/to/JsonObjectToConstraintTransformer.java
> +        //TODO check for type of constraint (atomic, and, or, ...)
created #2671

2023-04-04 08:58 UTC, merged