docs: add missing Extension annotaions and replace String with consta…
eclipse-edc/Connector pull request #2840
Opened 2023-04-28 09:23 UTC by majadlymhmd

…nt name

## What this PR changes/adds

Add missing Extension annotations and replace String with constant NAME
## Why it does that
to make the code more readable and improve code quality
_Briefly state why the change was necessary._

## Further notes

## Linked Issue(s)

ref #2710 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

2023-05-02 07:31 UTC, ndr-brt reviewed
Please override `name` method where the `NAME` constant is defined, and avoid changing formatting on the `{ }` thing

2023-05-02 07:31 UTC, ndr-brt commented on core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractNegotiationCommandExtension.java
> +    public static final String NAME = "Contract Negotiation command handler";
please override the `name` method and make it return the `NAME` constant as well

2023-05-02 07:31 UTC, ndr-brt commented on core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferProcessCommandExtension.java
> +    public static final String NAME = "Transfer Process Command";
ditto

2023-05-02 07:31 UTC, ndr-brt commented on extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyExtension.java
> +@Provides({WebServer.class, JettyService.class})
The default formatting for static array definitions should have the whitespace after open bracket and before closing bracket

2023-05-03 14:06 UTC, ndr-brt approved these changes

2023-05-04 07:38 UTC, juliapampus requested changes
Rest looks good 👍🏻

2023-05-04 07:38 UTC, juliapampus commented on extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/SqlContractNegotiationStoreExtension.java
> +@Provides({ContractNegotiationStore.class})
Whitespace seems to be still missing. See https://github.com/eclipse-edc/Connector/pull/2840#discussion_r1182185925

2023-05-04 07:38 UTC, juliapampus commented on extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractdefinition/SqlContractDefinitionStoreExtension.java
> +@Provides({ContractDefinitionStore.class})
whitespace

2023-05-04 07:38 UTC, juliapampus commented on extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndexServiceExtension.java
> +@Provides({AssetIndex.class, DataAddressResolver.class})
whitespace

2023-05-30 08:01 UTC, ndr-brt commented
@majadlymhmd could you resolve conflicts so we can merge?

2023-06-15 02:27 UTC, closed without merging