feat: move observability api from `management` to `default`
eclipse-edc/Connector pull request #3166
Opened 2023-06-12 08:09 UTC by ndr-brt

## What this PR changes/adds

Remove observability controller from management api and put on the default context as it was before the api context refactoring

## Why it does that

Untangling dependencies between an hi-level api as observability and the management api

## Further notes

-

## Linked Issue(s)

Closes #3165 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md)._

2023-06-13 05:35 UTC, paullatzelsperger approved these changes

2023-06-15 09:52 UTC, bscholtes1A requested changes

2023-06-16 06:41 UTC, ndr-brt commented on extensions/common/api/api-observability/src/test/java/org/eclipse/edc/api/observability/ObservabilityApiControllerTest.java
> +//@ApiTest
no, indeed! fixed, thanks

2023-06-16 07:54 UTC, bscholtes1A approved these changes

2023-06-16 08:26 UTC, merged