fix(api): add `baseUrl` to asset examples for v3 API
eclipse-edc/Connector pull request #3485
Opened 2023-09-29 14:15 UTC by saschaisele-zf

## What this PR changes/adds

Adds `baseUrl` to the input/output examples for the creation of an asset in the v3 API.

## Why it does that

Current example will be rejected with a `400 Bad Request`

## Linked Issue(s)

Closes #3476

2023-09-29 14:26 UTC, wolf4ood approved these changes

2023-09-29 15:11 UTC, wolf4ood requested changes

2023-09-29 15:11 UTC, wolf4ood commented on extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java
>                          "edc:type": "HttpData"
```suggestion
                        "edc:type": "HttpData",
```

2023-10-02 05:21 UTC, paullatzelsperger approved these changes
LGTM with @wolf4ood's change requests

2023-10-05 07:02 UTC, wolf4ood approved these changes

2023-10-05 07:20 UTC, merged