feat: Remove duplicate information in the initiate negotiation api request
eclipse-edc/Connector pull request #3605
Opened 2023-11-13 17:18 UTC by tuncaytunc-zf

## What this PR changes/adds

Removes the duplicate information in the initiate negotiation api request without increasing the API version

## Why it does that

The offer and the policy have some duplicate values like id and assetId which are representing the same information.

## Further notes

The offer will be logged as deprecates to avoid any braking changes

## Linked Issue(s)

Closes #3395 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

2023-11-15 14:20 UTC, tuncaytunc-zf commented on extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidator.java
> -                )
I have extended the Validation but the logs are still in Transformator

2023-11-15 14:20 UTC, tuncaytunc-zf commented on extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
> +                        }]
Fixed, thanks.

2023-11-16 07:47 UTC, ndr-brt requested changes
last little nit, after that we'll be ready to merge

2023-11-16 07:47 UTC, ndr-brt commented on extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
> +            Policy policy,
```suggestion
            ManagementApiSchema.PolicySchema policy,
```

2023-11-16 12:37 UTC, merged