refactor: make postgresql ITests use real database connections
eclipse-edc/Connector pull request #3678
Opened 2023-11-30 15:51 UTC by ndr-brt

## What this PR changes/adds

Fixes a tricky bug related to the `LocalTransactionContext`, specifically, in case that the block returned a `Stream`, the context finalized the connection (aka: commit/rollback and then close it) before the `Stream` could have been fully browsed.

For this in the `LocalTransactionContext` now in case the result is a `Stream` the `finalization` will be executed when the `Stream` will be closed ([we already stated that the `Stream`s coming out from the services need to be closed explicitly](https://github.com/eclipse-edc/Connector/blob/96734fc83067381ec3c8edc314af4627231b62e3/extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/QueryExecutor.java#L34-L38)).

There is an unit test on the class ensuring this and also a `PostgresLocalTransactionContextTest` integration test (that without the fix will throw the error reported in #3640)

## Why it does that

fix bug

## Further notes

- had to change `PostgresqlStoreSetupExtension` a lot to make it behave as the production code, I also refactored some code while going down to find the bug, I think the work I did is pretty valuable, e.g. :
  - moving `DefaultDataSourceRegistry` out of the `sql-pool-apache-commons` (it would need some other love but it could be done in the future)
  -  closing some streams that weren't closed correctly
  - other cosmetic improvements

## Linked Issue(s)

Closes #3640 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

2023-11-30 16:32 UTC, wolf4ood reviewed
:rocket:

2023-12-01 07:27 UTC, paullatzelsperger commented on extensions/common/transaction/transaction-local/src/main/java/org/eclipse/edc/transaction/local/LocalTransactionContext.java
>              if (transaction == null) {
nit: could be shortened to `if(transactions.get() == null)`

2023-12-01 07:50 UTC, jimmarino requested changes
Hey @ndr-brt I have some questions/comments about the proposed changes here that will be easier to discuss than enumerate. Let's go through them and we can summarize here later.

2023-12-01 10:37 UTC, ndr-brt commented
Close as it will be splitted in two parts

2023-12-01 10:37 UTC, closed without merging