docs: typed policy engine DR
eclipse-edc/Connector pull request #4526
Opened 2024-10-03 08:37 UTC by ndr-brt

## What this PR changes/adds

Adds DR for typed policy engine refactor

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Part of #3511 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

2024-10-04 05:54 UTC, paullatzelsperger commented on docs/developer/decision-records/2024-10-05-typed-policy-engine/README.md
> +We will implement a new implementation of the Policy Engine, with strongly typed scopes and contexts.
```suggestion
We will implement a new feature of the Policy Engine, with strongly typed scopes and `PolicyContext` objects.
```

2024-10-04 05:54 UTC, paullatzelsperger commented on docs/developer/decision-records/2024-10-05-typed-policy-engine/README.md
> +Other interfaces/classes will need to be duplicated with a "scoped" version of them, like:
How so? wouldn't all the functions get registered for a scope just as they are now? If I understood correctly, all the changes are done "under the hood", no?

2024-10-04 06:31 UTC, jimmarino requested changes
Let's discuss this further. I don't like having two implementations of the policy engine and I also do not want to eliminate hierarchical scopes as they are useful.

2024-10-04 06:31 UTC, jimmarino commented on docs/developer/decision-records/2024-10-05-typed-policy-engine/README.md
> +- scope hierarchy won't be a thing anymore (e.g. `scope` and `scope.child`)
This is used. Let's discuss this

2024-10-04 15:22 UTC, ndr-brt commented
@jimmarino @paullatzelsperger I revisited the DR scope, now is more narrow and it will permit to keep scopes hierarchy.

2024-10-09 14:05 UTC, ndr-brt commented
@jimmarino DR is ready to review

2024-10-10 06:38 UTC, jimmarino approved these changes
👍

2024-10-10 07:14 UTC, wolf4ood approved these changes

2024-10-10 07:22 UTC, merged