chore(DataPlanePublicAPI): Error message handling
eclipse-edc/Connector pull request #4678
Opened 2024-12-16 11:27 UTC by kkotowiczz

## What this PR changes/adds
Changed error handling method to be returned directly as list, instead of being concatenated first and then wrapped to the list

## Why it does that

In order to make an error response being more readable

## Further notes
N/A
## Linked Issue(s)
Closes #4670

2024-12-16 12:59 UTC, jimmarino requested changes
Please provide unit tests

2024-12-16 13:39 UTC, jimmarino requested changes
This PR does not properly test the changes. Please fix this.

2024-12-16 13:39 UTC, jimmarino commented on extensions/data-plane/data-plane-public-api-v2/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlanePublicApiV2ControllerTest.java
> +                .body("errors", is(List.class));
This test does not properly verify the change. Compare it to how the original test verifies the error messages.

2024-12-16 16:41 UTC, jimmarino commented
In the future, please:

1. Open an issue
2. After your issue has been approved, please create a DRAFT PR to avoid repetitive reviews.

Thx

2025-01-15 08:44 UTC, ndr-brt commented on extensions/data-plane/data-plane-public-api-v2/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlanePublicApiV2ControllerTest.java
> +        assertEquals(secondErrorMsg, errors.get(1));
you can use restassured to test this, like:
```
.body("errors[0]", is(firstErrorMsg)
```

2025-01-15 12:51 UTC, ndr-brt approved these changes
LGTM

2025-01-15 12:51 UTC, merged