Add resource parameter to the OAuth2 token request to follow RFC-8707
eclipse-edc/Connector pull request #4680
Opened 2024-12-17 16:25 UTC by scandinave

## What this PR changes/adds

This PR makes the OAuth2 implementation ask for a token with a resource from param to follow the RFC-8707. 

## Why it does that

This allows an IDP to set the correct `aud` claim in the access token given to the connector.

## Further notes

## Linked Issue(s)

Closes #4668

2024-12-18 07:12 UTC, scandinave commented
I've updated tests to validate the new parameter.

2024-12-18 07:22 UTC, jimmarino requested changes
This can change existing behavior in some cases. If the resource is not set as a param, it should not be set on the client OAuth request. 

Also, this should be an opt-in configuration parameter that is off by default (please document with `@Setting`). This behavior also needs to be tested.

2024-12-18 07:39 UTC, jimmarino commented
> I was thinking that the resource will always be set because there is always a counterPartyAddress right? Connector validates the audience of the access token when receiving request. If no resource is set, the audience will not match.
> 
> But I can definitely make a configurable option to enable this on demands for people that don't care about that.
> 
> I will rework my PR.

Yes, please do to preserve the existing behavior.

2024-12-18 15:21 UTC, scandinave commented
I've had a test in the Daps extension that highlight the current situation. It is called Rfc8707IntegrationTest. With this PR, if we have the DAPS extension that tells the IDP to set a specific audience and we also enabled the new resource parameter feature, the audience will have the value sent via the resource parameter. 

What behavior do you expect for this ? : 

* Always make the resource parameter do its job
* Make the Daps override the resource parameter
* Make the Daps throw a warning/error telling why it can't due its job.

2025-01-03 04:56 UTC, scandinave commented
Can you reopen this PR please ?

2025-01-06 09:49 UTC, jimmarino requested changes
Comments inline

2025-01-06 09:49 UTC, jimmarino commented on extensions/common/iam/oauth2/oauth2-daps/src/test/java/org/eclipse/edc/iam/oauth2/daps/Rfc8707IntegrationTest.java
> +/*
This header needs to be changed to your corporate sponsor that aligns with the CLA

2025-01-06 09:49 UTC, jimmarino commented on extensions/common/iam/oauth2/oauth2-daps/src/test/java/org/eclipse/edc/iam/oauth2/daps/Rfc8707IntegrationTest.java
> +public class Rfc8707IntegrationTest {
Please don't use an integration test for this as they slow down the build. Unit tests should cover this.

2025-01-06 13:27 UTC, scandinave commented on extensions/common/iam/oauth2/oauth2-daps/src/test/java/org/eclipse/edc/iam/oauth2/daps/Rfc8707IntegrationTest.java
> +public class Rfc8707IntegrationTest {
I have made this test because I found that the `DapsIntegrationTest` test fail if in used with the feature flag of this PR set to true. This test is to demonstrate the concomitance used of the Daps extension with the new feature but with a correct configuration. 
I don't know why someone would use both at the same time so if you think, it is not needed, I can remove it. The new feature is already covert by a updated unit test included in this PR.

2025-01-06 13:27 UTC, scandinave commented on extensions/common/iam/oauth2/oauth2-daps/src/test/java/org/eclipse/edc/iam/oauth2/daps/Rfc8707IntegrationTest.java
> +/*
In progress on our side

2025-01-06 13:41 UTC, jimmarino commented on extensions/common/iam/oauth2/oauth2-daps/src/test/java/org/eclipse/edc/iam/oauth2/daps/Rfc8707IntegrationTest.java
> +public class Rfc8707IntegrationTest {
Yes, please delete it. DAPs will be removed at some point as well as it is not a production-grade identity provider.

2025-01-06 15:04 UTC, scandinave commented
Unit test are in failure on the main branch. See #4699. Waiting for the correction.

2025-01-13 15:53 UTC, scandinave commented
@jimmarino Do I need to wait for a review by the second reviewer, or it is ok for you to merge this PR ?

2025-01-13 19:46 UTC, jimmarino requested changes
One minor change and it will be good to merge.

2025-01-13 19:46 UTC, jimmarino commented on extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImpl.java
> +        PrivateKeyOauth2CredentialsRequest.Builder<?> builder = Builder.newInstance()
Please use var

2025-01-13 21:30 UTC, scandinave commented on extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImpl.java
> +        PrivateKeyOauth2CredentialsRequest.Builder<?> builder = Builder.newInstance()
Done. Thanks for your support.

2025-01-14 12:43 UTC, jimmarino approved these changes

2025-01-14 12:43 UTC, merged